kpaas-io/kpaas

- .gitignore
- README.md
- cli/portal/main.go
- 由于每个人习惯不太一样，把编辑器设置加入.gitignore
- 增加说明：VSCoder的lisence插件推荐
> add VSCode auto licenser

- README.md
More detail please link to offical help documentation:
https://www.jetbrains.com/help/idea/copyright.html
> docs(README): Added steps to configure JetBrain IDE to automatically add copyright information

- charts/calico/Values.yaml
- charts/calico/templates/calico-node.yaml
> change default pod IP CIDR

- pkg/deploy/action/node_check_action.go
- pkg/deploy/action/node_check_executor.go
- pkg/deploy/consts/msg.go
- pkg/deploy/task/node_check_processor.go
1. added nodeCheckItem
2. added method to generate node check task summary based on its actions' status.
> feature(deploy): add nodeCheckItem for node check action

- go.mod
- pkg/deploy/action/action.go
- pkg/deploy/action/deploy_etcd_action.go
- pkg/deploy/action/deploy_etcd_executor.go
- pkg/deploy/action/executor.go
- pkg/deploy/action/node_check_action.go
- pkg/deploy/action/node_check_executor.go
- pkg/deploy/consts/misc.go
- pkg/deploy/consts/msg.go
- pkg/deploy/server/controller.go
- pkg/deploy/task/deploy_etcd_processor.go
- pkg/deploy/task/deploy_etcd_task.go
- pkg/deploy/task/deploy_processor.go
- pkg/deploy/task/deploy_task.go
- pkg/deploy/task/processor.go
- pkg/deploy/task/task.go
1. Add subtasks to the task/aciton framework
2. Add Priority property to Task interface
3. Update the Processor inteface
4. Refactor the way to start/execute a task
5. Implement the Deploy API and related deploy task.
> feature(deploy): add subtasks to the framework

- pkg/deploy/action/deploy_etcd_executor.go
- pkg/deploy/action/node_check_executor.go
- pkg/deploy/consts/misc.go
- pkg/deploy/task/deploy_etcd_processor.go
- pkg/deploy/task/deploy_processor.go
- pkg/deploy/task/node_check_processor.go
- pkg/deploy/task/processor.go
- pkg/utils/log/init.go
- pkg/utils/log/req_logger.go
- run/deploy/root.go
1.Setup log formatter for logurs to output file name, line nubmer and function name.
2.Remove unnecessary log fileds in deploy.
> feature(log): setup log formatter for logrus

- pkg/service/api/v1/helm/release.go
- pkg/service/model/api/helm.go
- pkg/service/swaggerdocs/docs.go
- pkg/service/swaggerdocs/swagger.json
- pkg/service/swaggerdocs/swagger.yaml
The swagger not support direct use map[string]interface{} , it will make build error.
> fix(service-helm): Fixed swagger init error

- Makefile
Because github not have swag, it can't make swag init
> build(github-action): Fixed make build on github action error

- pkg/deploy/action/node_check_action.go
- pkg/deploy/action/node_check_executor.go
- pkg/deploy/operation/check/check_system_preference.go
- pkg/deploy/operation/check/common.go
- pkg/deploy/scripts/check_system_preference.sh
更新如下：
1. 添加系统网络基础检查文件 CheckSysPreference.go, 主要为了检查 sysctl 下的 ipv4 等状态
2. 修改冗余函数，去除多余的 Update，因为该数组更新只有一次，所以数组内只有一条对应 item 数据，因此同时也可以将 func Update 移除
3. 去除了 check_system_preference.sh 中的 cali_interface 函数，脚本只检查基础的系统网络参数，在检查的时候没有指定网络模型，因此可以先去除
> feature(deploy/check): add system preference check, remove redundant function

- pkg/deploy/action/node_check_executor.go
- pkg/deploy/action/node_init_executor.go
- pkg/deploy/operation/check/check_cpu_num.go
- pkg/deploy/operation/check/check_docker_version.go
- pkg/deploy/operation/check/check_kernel_version.go
- pkg/deploy/operation/check/check_memory_capacity.go
- pkg/deploy/operation/check/check_root_disk_volume.go
- pkg/deploy/operation/check/check_system_distribution.go
- pkg/deploy/operation/check/check_system_preference.go
- pkg/deploy/operation/check/common.go
- pkg/deploy/operation/init/common.go
- pkg/deploy/operation/init/init_change_alias.go
- pkg/deploy/operation/init/init_change_firewall.go
- pkg/deploy/operation/init/init_change_hostname.go
- pkg/deploy/operation/init/init_change_network.go
- pkg/deploy/operation/init/init_change_route.go
- pkg/deploy/operation/init/init_change_swap.go
- pkg/deploy/operation/init/init_change_timezone.go
- pkg/service/grpcutils/mock/deploy_controller.go
2019.12.13
1. 补充 close ssh client
2. 修改语法更美观
> fix(deploy/check&init): add close ssh client

- pkg/service/api/v1/helm/action_config.go
- pkg/service/api/v1/helm/release.go
- pkg/service/api/v1/helm/rollback_release.go
- pkg/service/api/v1/helm/uninstall_release.go
- pkg/service/api/v1/helm/upgrade_release.go
- pkg/service/swaggerdocs/docs.go
- pkg/service/swaggerdocs/swagger.json
- pkg/service/swaggerdocs/swagger.yaml
Implement the following APIs in helm:
- UpgradeRelease upgrades an installed release
- RollbackRelease rollbacks a release to a previous version
- UinstallRelease uninstalls a release and delete the resources created for it
> feature(service/helm) implement UpgradeRelase,RollbackRelease,UninstallRelease APIs #OONE-19 #OONE-93

- pkg/constant/machine_roles.go
- pkg/deploy/consts/enum.go
- pkg/deploy/task/deploy_processor.go
- pkg/deploy/task/deploy_task.go
- pkg/service/model/api/node.go
Unified machine role constants
> refactor(machine-role): Refactoring duplicated machine role constants use

- pkg/service/api/v1/helm/export_release.go
- pkg/service/api/v1/helm/get_release.go
- pkg/service/api/v1/helm/install_release.go
- pkg/service/api/v1/helm/list_release.go
- pkg/service/api/v1/helm/release.go
- pkg/service/api/v1/helm/render_template.go
- pkg/service/api/v1/helm/rollback_release.go
- pkg/service/api/v1/helm/uninstall_release.go
- pkg/service/api/v1/helm/upgrade_release.go
- pkg/service/model/api/helm.go
- pkg/service/swaggerdocs/docs.go
- pkg/service/swaggerdocs/swagger.json
- pkg/service/swaggerdocs/swagger.yaml
implement the following APIs:
- GetRelease to get information of an installed release
- ListRelease to list all installed releases in a namespace
- ExportRelease to download the manifest of an installed release
- RenderTemplate to render a chart with specified values
> implement helm APIs: GetRelease,ExportRelease,ListRelease,RenderTemplate

- pkg/deploy/action/node_init_executor.go
- pkg/deploy/consts/deploy.go
- pkg/deploy/operation/init/common.go
- pkg/deploy/operation/init/init_deploy_kubetool.go
- pkg/deploy/operation/worker/join.go
- pkg/deploy/scripts/init_deploy_kubetool.sh
1. 添加安装 kubeadm, kubectl, kubelet 的代码
2. 配置 kubelet.conf 于 /etc/system/systemd 中
3. daemon-reload
> feature(deploy/init): add install kubeTool

- pkg/deploy/operation/check/common.go
- pkg/deploy/operation/init/common.go
> fix(deploy): modify itemEnum to string

- pkg/deploy/command/shell.go
- pkg/deploy/machine/lib.go
> test(deploy/check): fix SSH exec return order

- pkg/deploy/action/node_init_executor.go
- pkg/deploy/machine/client.go
- pkg/deploy/machine/machine.go
- pkg/deploy/operation/init/init_change_alias.go
- pkg/deploy/operation/init/init_change_firewall.go
- pkg/deploy/operation/init/init_change_hostname.go
- pkg/deploy/operation/init/init_change_network.go
- pkg/deploy/operation/init/init_change_route.go
- pkg/deploy/operation/init/init_change_swap.go
- pkg/deploy/operation/init/init_change_timezone.go
- pkg/deploy/operation/init/init_deploy_haproxy.go
- pkg/deploy/operation/init/init_deploy_keepalived.go
- pkg/deploy/operation/init/init_deploy_kubetool.go
- pkg/deploy/scripts/init_change_route.sh
- pkg/deploy/task/deploy_processor.go
- test/deploy/api_data.go
1. 添加 debug，增加 error 信息供调试
2. 暂时去除 keepalived 及 haproxy 部署，不影响 k8s 部署
3. 修改 ssh client 关闭方式，判断 m 是否创建，增加关闭 sftp 判断
> test(deploy/init): add debug, add error print

- pkg/constant/check_result.go
- pkg/service/api/v1/deploy/convert.go
- pkg/service/api/v1/deploy/convert_test.go
- pkg/service/api/v1/deploy/deploy.go
- pkg/service/api/v1/deploy/deploy_test.go
- pkg/service/model/wizard/cluster.go
Making deploy controller operation status convert to deploy service check and deploy status.
> feat(deploy-service): Rematch deploy controller check status, deploy status, deploy cluster status.

- pkg/deploy/action/node_check_executor.go
- pkg/deploy/action/node_init_executor.go
- pkg/deploy/operation/check/common.go
- test/deploy/api_data.go
1. 修改 mock data 的格式
2. 修改 description 为中文
> test(deploy/check): modify test data format

- pkg/deploy/operation/common.go
- pkg/deploy/operation/init/common.go
- pkg/deploy/operation/init/init_change_alias.go
- pkg/deploy/operation/init/init_change_firewall.go
- pkg/deploy/operation/init/init_change_hostname.go
- pkg/deploy/operation/init/init_change_network.go
- pkg/deploy/operation/init/init_change_route.go
- pkg/deploy/operation/init/init_change_swap.go
- pkg/deploy/operation/init/init_change_timezone.go
- pkg/deploy/operation/init/init_deploy_haproxy.go
- pkg/deploy/operation/init/init_deploy_keepalived.go
- pkg/deploy/operation/init/init_deploy_kubetool.go
- pkg/deploy/operation/worker/join.go
调整 init_deploy_kubetool.sh 的位置，join node 可以读取到脚本
> test(deploy): fix deploy master/worker script path

- pkg/deploy/operation/worker/join.go
> fix(deploy/join): fix join node to master

- pkg/deploy/action/connectivity_check_test.go
- pkg/deploy/action/deploy_etcd_test.go
- pkg/deploy/action/deploy_worker_test.go
- pkg/deploy/action/fetch_kube_config_test.go
- pkg/deploy/action/init_master_test.go
- pkg/deploy/action/join_master_test.go
- pkg/deploy/action/node_check_test.go
- pkg/deploy/action/node_init_test.go
- pkg/deploy/action/test_connection_test.go
- pkg/deploy/lib.go
- pkg/deploy/machine/machine.go
- pkg/deploy/machine/mock_machine.go
- pkg/deploy/operation/etcd/etcd.go
- pkg/deploy/operation/master/init.go
- pkg/deploy/task/deploy_etcd_processor.go
Signed-off-by: congcongke <zhanweidu@163.com>
> test(deploy/api): add ut test

- .github/workflows/develop-release.yml
- .github/workflows/develop.yml
- .github/workflows/pr.yml
- builds/docker/kpaas/Dockerfile
- builds/docker/kpaas/dashboard.conf
- run/docker/entrypoint.sh
https://kpaas.atlassian.net/wiki/spaces/kpaas/pages/93585445/Github+Workflow
> ci(github-action): Added kpaas dashborad into docker image when develop merged

- go.mod
- go.sum
- pkg/deploy/action/deploy_worker_executor.go
- pkg/deploy/operation/worker/annotation.go
- pkg/deploy/operation/worker/label.go
- pkg/deploy/operation/worker/taint.go
修复 taint, label, annotation 逻辑
> fix(deploy): fix add node to master taint,annotation,label

- pkg/deploy/action/connectivity_check_action.go
- pkg/deploy/operation/master/init.go
> fix(deploy): fix typo

- pkg/deploy/operation/master/join.go
…void condition race and dirty content
> fix(deploy/join-master): fetch kube config to a temp unique file to avoid condition race and dirty content

- pkg/deploy/action/node_check_executor.go
- pkg/deploy/action/node_init_executor.go
- pkg/deploy/operation/check/check_cpu_num.go
- pkg/deploy/operation/check/check_docker_version.go
- pkg/deploy/operation/check/check_kernel_version.go
- pkg/deploy/operation/check/check_memory_capacity.go
- pkg/deploy/operation/check/check_port_occupied.go
- pkg/deploy/operation/check/check_root_disk_volume.go
- pkg/deploy/operation/check/check_system_distribution.go
- pkg/deploy/operation/check/check_system_manager.go
- pkg/deploy/operation/check/check_system_preference.go
- pkg/deploy/operation/check/common.go
- pkg/deploy/operation/init/common.go
- pkg/deploy/operation/init/init_change_alias.go
- pkg/deploy/operation/init/init_change_firewall.go
- pkg/deploy/operation/init/init_change_hostname.go
- pkg/deploy/operation/init/init_change_network.go
- pkg/deploy/operation/init/init_change_route.go
- pkg/deploy/operation/init/init_change_swap.go
- pkg/deploy/operation/init/init_change_timezone.go
- pkg/deploy/operation/init/init_deploy_haproxy.go
- pkg/deploy/operation/init/init_deploy_keepalived.go
- pkg/deploy/operation/init/init_deploy_kubetool.go
- pkg/deploy/operation/operation.go
优化代码:
1. 创建 ssh 后添加 Do 命令，执行 Do 命令之后，defer 关闭 ssh 连接，去除冗余代码，~~只实现 check 部分~~，实现了 check 及 init
------Updated 2020.1.9 11:16
1. 修改了 check&init 的创建 operation 逻辑，精简了 CheckOperation, InitOperation
> fix(deploy): optimize check&init code

- go.mod
- pkg/deploy/action/init_master_action.go
- pkg/deploy/action/init_master_executor.go
- pkg/deploy/action/join_master_action.go
- pkg/deploy/action/join_master_executor.go
- pkg/deploy/consts/deploy.go
- pkg/deploy/lib.go
- pkg/deploy/operation/common.go
- pkg/deploy/operation/master/init.go
- pkg/deploy/operation/master/join.go
- pkg/deploy/task/deploy_master_processor.go
- pkg/deploy/task/deploy_master_task.go
- pkg/deploy/task/deploy_processor.go
- pkg/deploy/task/init_master_processor.go
- pkg/deploy/task/init_master_task.go
- pkg/deploy/task/join_master_processor.go
- pkg/deploy/task/join_master_task.go
- AlreadyJoin already relocated to a common function as below:
```
func AlreadyJoined(hostname string, masterNode *pb.Node) (bool, error) {
```
Call it as you need
> feature(deploy/master): add master multi-role support

- pkg/deploy/action/node_check_executor.go
- pkg/deploy/operation/check/check_cpu_num.go
- pkg/deploy/operation/check/check_docker_version.go
- pkg/deploy/operation/check/check_kernel_version.go
- pkg/deploy/operation/check/check_memory_capacity.go
- pkg/deploy/operation/check/check_port_occupied.go
- pkg/deploy/operation/check/check_root_disk_volume.go
- pkg/deploy/operation/check/check_system_distribution.go
- pkg/deploy/operation/check/check_system_manager.go
- pkg/deploy/operation/check/check_system_preference.go
- pkg/deploy/operation/check/common.go
添加 check 检查写入日志
1. 使用 log channel 实现并发 check 的 buffer 收集
2. 统一把 log channel 写到 action 对应的 act.GetExecuteLog 中
> feat(deploy/check): add check log #OTWO-12

- pkg/deploy/action/init_master_executor.go
- pkg/deploy/operation/master/init.go
Signed-off-by: congcongke <zhanweidu@163.com>
> feat(deploy/log): add log for deploy master

- pkg/deploy/action/deploy_etcd_executor.go
- pkg/deploy/action/join_master_executor.go
- pkg/deploy/operation/etcd/etcd.go
- pkg/deploy/operation/master/join.go
Signed-off-by: congcongke <zhanweidu@163.com>
> feat(deploy/log): write log to file for deploy etcd/join operation

- pkg/deploy/operation/check/check_cpu_num.go
- pkg/deploy/operation/check/check_docker_version.go
- pkg/deploy/operation/check/check_kernel_version.go
- pkg/deploy/operation/check/check_memory_capacity.go
- pkg/deploy/operation/check/check_port_occupied.go
- pkg/deploy/operation/check/check_root_disk_volume.go
- pkg/deploy/operation/check/check_system_distribution.go
- pkg/deploy/operation/check/check_system_manager.go
- pkg/deploy/operation/check/check_system_preference.go
- pkg/deploy/operation/init/init_change_alias.go
- pkg/deploy/operation/init/init_change_firewall.go
- pkg/deploy/operation/init/init_change_hostname.go
- pkg/deploy/operation/init/init_change_network.go
- pkg/deploy/operation/init/init_change_route.go
- pkg/deploy/operation/init/init_change_swap.go
- pkg/deploy/operation/init/init_change_timezone.go
- pkg/deploy/operation/init/init_deploy_haproxy.go
- pkg/deploy/operation/init/init_deploy_keepalived.go
- pkg/deploy/operation/init/init_deploy_kubetool.go
函数内关闭 ssh client 已经做过 machine 是否为空的检查，不用重复判断，直接关闭即可
> fix(deploy): code opt

- pkg/deploy/action/connectivity_check_action.go
- pkg/deploy/consts/enum.go
- pkg/deploy/machine/lib.go
- pkg/deploy/task/check_network_requirements.go
- pkg/deploy/task/node_check_processor.go
- test/deploy/api_data.go
- 使用`echo > /dev/tcp(udp)`代替`nc`发送数据包
- `calicoOptions`为空时，提供默认选项
- 检查项详情使用中文
> fix(deploy/check-network) send packet using /dev/tcp(udp)

- pkg/service/model/api/wizard.go
- pkg/service/swaggerdocs/docs.go
- pkg/service/swaggerdocs/swagger.json
- pkg/service/swaggerdocs/swagger.yaml
Removed Progress And Mode Fields
> feat(deploy-service): Removed get wizard data no need fields
